[package]
name = "rskit"
version = "0.0.2"
edition = "2021"
license = "MIT"
description="rust kit"
repository = "https://github.com/itooling/rskit"


[lib]


[dependencies]
log = "0.4.21"
fast_log = "1.6.12"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
