[package]
name = "rskit"
version = "0.0.1"
edition = "2021"
license = "MIT"
description="rust kit"


[lib]


[dependencies]
log = "0.4.21"
fast_log = "1.6.12"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
